### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by logwin** [peregrine-collegia/POD#4]
Hello

With the mod, the game crashed while selecting a beginning date for the game.  There's nothing else, the text appears to make the description of the time period and when the character should appears, the game crashes and windows throws an error.

My CK2 version : 2.3.2 (MMUR)

**Comment by flintsparc** [comment]
Known issue.  See the forums discussion.  I hope to get some time to work on it too, but the 2.3.2 vanilla patch broke the mod.  If you revert to an earlier version of vanilla, the mod will work.

The problem seems to be in history/provinces and history/titles    

I'm currently in the slow process of redoing them all, and hopefully in a manner that will allow for easier modification in the future.

**Comment by Leorgrium** [comment]
thanks for your time:)
I hope you could fix it soon :+1:

**Comment by flintsparc** [comment]
See version 0.3.0
